### ISSUE TITLE
redistributable for mac not working

### ISSUE THREAD

**Issue by josuigoa** [deepnight/ld45#1]
Hi!

I think the game was created for a different HL version than the given one. Double clicking `sabotage` file opens a terminal window with the message 'FATAL ERROR: Failed to load function std@bytes_compare16'. Putting the `libhl.dylib` of HL 1.10 it tells me that `FATAL ERROR: Failed to load library fmt.hdll`. I can't go further, I don't know what can it be.

Of course, it works if `hl sabotage.mac/hlboot.dat`, but it isn't the point.

**Comment by deepnight** [comment]
Yes, the Mac redist was never tested: I should update the RedistHelper haxelib to make it work properly at some point. Sorry about that :)

**Comment by josuigoa** [comment]
Don't worry. I've played the game online (nice game btw!) but in this case I was interested in the distribution, since I can't distribute my own app with another mac users :(

**Comment by deepnight** [comment]
Opened https://github.com/deepnight/deepnightLibs/issues/5
